org: yishida3

service: serverless-framework-tutorial

custom:
  defaultStage: dev

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.12
  profile: serverless-tutorial-agent
  stage: ${opt:stage, self:custom.defaultStage}
  ecr:
    images:
      containerLambda:
        path: ./src

functions:
  hello:
    # name: ${self:service}-hello-${self:provider.stage}
    image:
      name: containerLambda
      command: src.handler.hello
    events:
      - http:
          path: /
          method: get