org: yishida3

service: serverless-framework-tutorial

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-plugin-ifelse

custom:
  defaultStage: dev
  apigwBinary:
    types:
      - multipart/form-data
  serverlessIfElse:
    - If: '"${opt:stage}" != "local"'
      Exclude:
        - functions.hello.handler

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.12
  profile: serverless-tutorial-agent
  stage: ${opt:stage, self:custom.defaultStage}
  ecr:
    images:
      container-lambda:
        path: ./api

functions:
  hello:
    # name: ${self:service}-hello-${self:provider.stage}
    handler: api.handler.hello
    image:
      name: container-lambda
      command: api.handler.hello
    events:
      - http:
          path: /
          method: any